[package]
name = "revolt_little_exif"

version = "0.4.0"
edition = "2021"

description = """
(fork which includes support for passing filetype directly)

This little library implements simple functionality for basic reading and 
writing of EXIF (related) metadata for PNG and JP(E)G image files (other file 
types - e.g. TIFF or HEIC - are planned for the future), with the advantage of 
being solely written in Rust & not relying on any 3rd party (C-)library for 
accessing the data (there are dependencies e.g. for calculating checksums or 
(de)compressing - however, they are also written in Rust). 
"""

authors = ["Tobias Prisching"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/revoltchat/little_exif"
readme = "README.md"
keywords = ["metadata", "exif", "photo", "image"]
categories = ["multimedia::images"]

exclude = [
    ".DS_Store",
    "**/.DS_Store",
    ".gitignore",
    "additional-documentation/*",
    "tests/*",
    ".cargo_vcs_info.json",
]

[dependencies]
crc = "3.0.0"
paste = "1.0.9"
miniz_oxide = "0.8.0"

[[test]]
name = "tests"
path = "tests/main.rs"
