[package]
name = "revolt_little_exif"

version = "0.5.1"
edition = "2021"

description = """
(fork which includes support for passing filetype directly)

Basic reading and writing of EXIF (related) metadata for PNG, JP(E)G, JXL and 
WebP image files (other file types - e.g. TIFF or HEIC - are planned), with the 
advantage of being solely written in Rust & not relying on any 3rd party 
non-rust library.
"""

authors = ["Tobias Prisching"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/revoltchat/little_exif"
readme = "README.md"
keywords = ["metadata", "exif", "photo", "image"]
categories = ["multimedia::images"]

exclude = [
    ".DS_Store",
    "**/.DS_Store",
    ".gitignore",
    "additional-documentation/*",
    "tests/*",
    ".cargo_vcs_info.json",
]

[dependencies]
crc = "3.0.0"
paste = "1.0.9"
miniz_oxide = "0.8.0"

[[test]]
name = "tests"
path = "tests/main.rs"
